nodeLinker: node-modules

npmRegistryServer: 'http://svn.xjjchain.com:8081/repository/npm-g'

unsafeHttpWhitelist:
  - 'svn.xjjchain.com'

yarnPath: .yarn/releases/yarn-sources.cjs

enableGlobalCache: true
